// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaybillSearchApp.Data;

#nullable disable

namespace WaybillSearchApp.Migrations
{
    [DbContext(typeof(WaybillContext))]
    partial class WaybillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaybillSearchApp.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Breadth")
                        .HasColumnType("double precision");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<double>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WaybillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcelNumber")
                        .IsUnique();

                    b.HasIndex("WaybillId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("WaybillSearchApp.Models.Waybill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RecipientPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientSuburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderSuburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaybillNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WaybillNumber")
                        .IsUnique();

                    b.ToTable("Waybills");
                });

            modelBuilder.Entity("WaybillSearchApp.Models.Parcel", b =>
                {
                    b.HasOne("WaybillSearchApp.Models.Waybill", "Waybill")
                        .WithMany("Parcels")
                        .HasForeignKey("WaybillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waybill");
                });

            modelBuilder.Entity("WaybillSearchApp.Models.Waybill", b =>
                {
                    b.Navigation("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
